switch from vue-style-loader to style-loader
nextcloud/social pull request #984
Opened 2020-08-25 16:53 UTC by icewind1991

vue-style-loader is unmaintained, broken with css-loader 4.x and regular style-loader now works properly with vue

this fixes styles not being loaded

2020-08-25 16:57 UTC, juliushaertl approved these changes

2020-08-25 18:18 UTC, juliushaertl requested changes, later dismissed

2020-08-25 18:18 UTC, juliushaertl commented on package.json
> -		"vue-style-loader": "^4.1.1",
Needs style-loader to be added as a dev dependency

2020-08-26 13:14 UTC, violoncelloCH approved these changes

2020-09-01 15:46 UTC, daita commented
sorry, can you please rebase ?

2020-09-01 15:46 UTC, ArtificialOwl approved these changes

2020-09-01 23:15 UTC, merged