👌 IMPROVE: composer
nextcloud/social pull request #996
Opened 2020-09-02 14:37 UTC by violoncelloCH

- button in appnavigation to create post -> open modal
- composer in timeline not sticky
- reply opens composer in modal
- use vuex to store composer reply and modal open state

TODO:
- [ ] store complete composer state in vuex so it doesn't get lost when composer modal is closed (accidentally) 
- [ ] Visibility button should have text next to it:
  - "Visible publicly", "Unlisted", "Visible to followers"
  - Post button could only say "Post"
  - "Direct message" should not show here
- [ ] composer input placeholder should be shown if composer is empty again
- [ ] allow to post image without text
- [ ] immediate feedback about sent post

2020-10-15 15:43 UTC, jancborchardt commented
Nice with the posting modal from anywhere! 2 issues:
- [ ] Attachments don’t show (note they show in the main composer in the background)
- [ ] The visibility dropdown is cut off by the edge of the modal on the bottom

![image](https://user-images.githubusercontent.com/925062/96153365-e66fa500-0f0d-11eb-9168-eb00ff63dd8f.png)

2020-10-18 18:12 UTC, violoncelloCH commented
thanks @jancborchardt for the feedback
sadly I currently don't have time to continue working on this... so @icewind1991 (or anyone else) if you want to continue on this one feel free...

some further points we should probably do in this PR as they touch the composer quite fundamentally:
- [ ] use the new RichContenteditable component: https://nextcloud-vue-components.netlify.app/#/Components/RichContenteditable 
- [ ] use the emojipicker component (#1039): https://nextcloud-vue-components.netlify.app/#/Components/EmojiPicker
- [ ] submit buttons and privacy popover should also use the proper components

2023-01-23 22:01 UTC, violoncelloCH commented
Hi, 
Same as in #744: even though this isn't finished I think there is still some notable improvements in here which would be worth a rebase...

2023-05-16 13:21 UTC, jancborchardt commented
@ArtificialOwl let’s not close longstanding pull requests without comment – reopening. :)

2025-09-04 08:40 UTC, jancborchardt requested changes
Still a very nice improvement and my review from above still stands. FYI @ArtificialOwl 

> Nice with the posting modal from anywhere! 2 issues:
> - [ ] Attachments don’t show (note they show in the main composer in the background)
> - [ ] The visibility dropdown is cut off by the edge of the modal on the bottom
> 
> ![image](https://user-images.githubusercontent.com/925062/96153365-e66fa500-0f0d-11eb-9168-eb00ff63dd8f.png)
>

2026-09-08 07:08 UTC, karlitschek commented
Closing after a triage of all open PRs: this targets the Vue-2-era `App.vue`, which has since been rewritten, so the patch no longer applies. A "new post" affordance in the navigation would still be a fine idea — feel free to open an issue for it against the current frontend. Thanks for the contribution.

2026-09-08 07:08 UTC, closed without merging